Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,6 +11,7 @@ env:
   ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
   ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
   IMAGE_TAG: latest
+  WEBSITE_URL: http://ALB-web-212639990.ap-southeast-1.elb.amazonaws.com
 
 jobs:
   deploy:
@@ -18,6 +19,17 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      # ===== TELEGRAM START =====
+      - name: Notify Deploy Started
+        run: |
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+          -d text="🚀 Deploy started
+
+          Repository: ${{ github.repository }}
+          Branch: ${{ github.ref_name }}
+          Actor: ${{ github.actor }}"
+
       - name: Checkout source code
         uses: actions/checkout@v4
 
@@ -59,5 +71,45 @@ jobs:
             --cluster $ECS_CLUSTER \
             --services $ECS_SERVICE
 
+      # ===== WEBSITE HEALTH CHECK =====
+      - name: Check Website Health
+        run: |
+          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $WEBSITE_URL)
+
+          echo "Website status code: $STATUS"
+
+          if [ "$STATUS" != "200" ]; then
+            echo "Website health check failed"
+            exit 1
+          fi
+
       - name: Deploy Success
         run: echo "Deployment completed successfully"
+
+      # ===== TELEGRAM SUCCESS =====
+      - name: Telegram Success Notification
+        if: success()
+        run: |
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+          -d text="✅ Deploy SUCCESS
+
+          Repository: ${{ github.repository }}
+          Commit: ${{ github.sha }}
+
+          ECS Service: ${{ env.ECS_SERVICE }}
+          Website: ${{ env.WEBSITE_URL }}
+          Status: Healthy (200 OK)"
+
+      # ===== TELEGRAM FAIL =====
+      - name: Telegram Failed Notification
+        if: failure()
+        run: |
+          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
+          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
+          -d text="❌ Deploy FAILED
+
+          Repository: ${{ github.repository }}
+          Branch: ${{ github.ref_name }}
+
+          Check GitHub Actions logs."
